
Tensor utilities
----------------------------------

.. currentmodule:: fastsom.core.tensor

:hidden:`index_tensor`
~~~~~~~~~~~~~~~~~~~~~~

.. autofunction:: index_tensor

:hidden:`expanded_op`
~~~~~~~~~~~~~~~~~~~~~

.. autofunction:: expanded_op

:hidden:`idxs_2d_to_1d`
~~~~~~~~~~~~~~~~~~~~~~~

.. autofunction:: idxs_2d_to_1d

:hidden:`idxs_1d_to_2d`
~~~~~~~~~~~~~~~~~~~~~~~

.. autofunction:: idxs_1d_to_2d
