
Miscellaneous
-------------

.. currentmodule:: fastsom.core.utils

:hidden:`ifnone`
~~~~~~~~~~~~~~~~

.. autofunction:: ifnone

:hidden:`ifindict`
~~~~~~~~~~~~~~~~~~

.. autofunction:: ifindict

:hidden:`is_iterable`
~~~~~~~~~~~~~~~~~~~~~

.. autofunction:: is_iterable

:hidden:`listify`
~~~~~~~~~~~~~~~~~

.. autofunction:: listify

:hidden:`setify`
~~~~~~~~~~~~~~~~

.. autofunction:: setify

:hidden:`compose`
~~~~~~~~~~~~~~~~~

.. autofunction:: compose

:hidden:`enum_eq`
~~~~~~~~~~~~~~~~~

.. autofunction:: enum_eq

